### ISSUE TITLE
After run on AVM it crash 

### ISSUE THREAD

**Issue by EtanaAlemu** [aimardcr/AndroidNativeGuard#8]
2024-04-22 19:57:00.364  9350-9350  ziparchive              id.kuro.androidnativeguard           W  Unable to open '/data/app/~~uwBAHh5UHxiDay8_yvHIog==/id.kuro.androidnativeguard-XjDfxUx1gjiddkaGTYJzsQ==/base.dm': No such file or directory
2024-04-22 19:57:00.364  9350-9350  ziparchive              id.kuro.androidnativeguard           W  Unable to open '/data/app/~~uwBAHh5UHxiDay8_yvHIog==/id.kuro.androidnativeguard-XjDfxUx1gjiddkaGTYJzsQ==/base.dm': No such file or directory
2024-04-22 19:57:00.792  9350-9350  nativeloader            id.kuro.androidnativeguard           D  Configuring classloader-namespace for other apk /data/app/~~uwBAHh5UHxiDay8_yvHIog==/id.kuro.androidnativeguard-XjDfxUx1gjiddkaGTYJzsQ==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~uwBAHh5UHxiDay8_yvHIog==/id.kuro.androidnativeguard-XjDfxUx1gjiddkaGTYJzsQ==/lib/x86_64:/data/app/~~uwBAHh5UHxiDay8_yvHIog==/id.kuro.androidnativeguard-XjDfxUx1gjiddkaGTYJzsQ==/base.apk!/lib/x86_64, permitted_path=/data:/mnt/expand:/data/user/0/id.kuro.androidnativeguard
2024-04-22 19:57:00.816  9350-9350  GraphicsEnvironment     id.kuro.androidnativeguard           V  ANGLE Developer option for 'id.kuro.androidnativeguard' set to: 'default'
2024-04-22 19:57:00.817  9350-9350  GraphicsEnvironment     id.kuro.androidnativeguard           V  ANGLE GameManagerService for id.kuro.androidnativeguard: false
2024-04-22 19:57:00.817  9350-9350  GraphicsEnvironment     id.kuro.androidnativeguard           V  Neither updatable production driver nor prerelease driver is supported.
2024-04-22 19:57:00.866  9350-9350  NetworkSecurityConfig   id.kuro.androidnativeguard           D  No Network Security Config specified, using platform default
2024-04-22 19:57:00.872  9350-9350  NetworkSecurityConfig   id.kuro.androidnativeguard           D  No Network Security Config specified, using platform default
2024-04-22 19:57:00.960  9350-9374  libEGL                  id.kuro.androidnativeguard           D  loaded /vendor/lib64/egl/libEGL_emulation.so
2024-04-22 19:57:00.963  9350-9374  libEGL                  id.kuro.androidnativeguard           D  loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
2024-04-22 19:57:00.969  9350-9374  libEGL                  id.kuro.androidnativeguard           D  loaded /vendor/lib64/egl/libGLESv2_emulation.so
2024-04-22 19:57:01.030  9350-9350  AppCompatDelegate       id.kuro.androidnativeguard           D  Checking for metadata for AppLocalesMetadataHolderService : Service not found
2024-04-22 19:57:01.233  9350-9350  roidnativeguard         id.kuro.androidnativeguard           W  Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
2024-04-22 19:57:01.234  9350-9350  roidnativeguard         id.kuro.androidnativeguard           W  Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
2024-04-22 19:57:01.242  9350-9350  Compatibil...geReporter id.kuro.androidnativeguard           D  Compat change id reported: 210923482; UID 10159; state: ENABLED
2024-04-22 19:57:01.317  9350-9350  roidnativeguard         id.kuro.androidnativeguard           A  runtime.cc:2397] Thread[1,tid=9350,Native,Thread*=0x7f4c4baae7b0,peer=0x713bbf58,"main"] attempting to detach while still running code
2024-04-22 19:57:01.581  9350-9350  roidnativeguard         id.kuro.androidnativeguard           A  runtime.cc:676] Runtime aborting...
                                                                                                    runtime.cc:676] Dumping all threads without mutator lock held
                                                                                                    runtime.cc:676] All threads:
                                                                                                    runtime.cc:676] DALVIK THREADS (18):
                                                                                                    runtime.cc:676] "main" prio=10 tid=1 Runnable
                                                                                                    runtime.cc:676]   | group="" sCount=0 ucsCount=0 flags=0 obj=0x713bbf58 self=0x7f4c4baae7b0
                                                                                                    runtime.cc:676]   | sysTid=9350 nice=-10 cgrp=top-app sched=0/0 handle=0x7f4d932f24f8
                                                                                                    runtime.cc:676]   | state=R schedstat=( 780012096 282451382 453 ) utm=53 stm=24 core=3 HZ=100
                                                                                                    runtime.cc:676]   | stack=0x7ffedbb60000-0x7ffedbb62000 stackSize=8188KB
                                                                                                    runtime.cc:676]   | held mutexes= "abort lock" "mutator lock"(shared held)
                                                                                                    runtime.cc:676]   native: #00 pc 000000000071ed04  /apex/com.android.art/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+132) (BuildId: 44bc52550248fc712a381bef164b75c7)
                                                                                                    runtime.cc:676]   native: #01 pc 0000000000842dfe  /apex/com.android.art/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+334) (BuildId: 44bc52550248fc712a381bef164b75c7)
                                                                                                    runtime.cc:676]   native: #02 pc 0000000000862cf8  /apex/com.android.art/lib64/libart.so (art::DumpCheckpoint::Run(art::Thread*)+1256) (BuildId: 44bc52550248fc712a381bef164b75c7)
                                                                                                    runtime.cc:676]   native: #03 pc 000000000085bfad  /apex/com.android.art/lib64/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+493) (BuildId: 44bc52550248fc712a381bef164b75c7)
                                                                                                    runtime.cc:676]   native: #04 pc 000000000085b1cf  /apex/com.android.art/lib64/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool)+2367) (BuildId: 44bc52550248fc712a381bef164b75c7)
                                                                                                    runtime.cc:676]   native: #05 pc 000000000080551e  /apex/com.android.art/lib64/libart.so (art::AbortState::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+174) (BuildId: 44bc52550248fc712a381bef164b75c7)
                                                                                                    runtime.cc:676]   native: #06 pc 00000000007ed875  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1381) (BuildId: 44bc52550248fc712a381bef164b75c7)
                                                                                                    runtime.cc:676]   native: #07 pc 0000000000019cfc  /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+60) (BuildId: 0aa332cd750579dec074c73abcd15956)
                                                                                                    runtime.cc:676]   native: #08 pc 000000000001924e  /apex/com.android.art/lib64/libbase.so (android::base::LogMessage::~LogMessage()+350) (BuildId: 0aa332cd750579dec074c73abcd15956)
                                                                                                    runtime.cc:676]   native: #09 pc 00000000007ed190  /apex/com.android.art/lib64/libart.so (art::Runtime::DetachCurrentThread()+272) (BuildId: 44bc52550248fc712a381bef164b75c7)
                                                                                                    runtime.cc:676]   native: #10 pc 0000000000600b9c  /apex/com.android.art/lib64/libart.so (art::JII::DetachCurrentThread(_JavaVM*)+44) (BuildId: 44bc52550248fc712a381bef164b75c7)
                                                                                                    runtime.cc:676]   native: #11 pc 00000000005f75df  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::CheckJII::DetachCurrentThread(_JavaVM*) (.llvm.10455603497705050653)+111) (BuildId: 44bc52550248fc712a381bef164b75c7)
                                                                                                    runtime.cc:676]   native: #12 pc 00000000000328c5  /data/app/~~uwBAHh5UHxiDay8_yvHIog==/id.kuro.androidnativeguard-XjDfxUx1gjiddkaGTYJzsQ==/lib/x86_64/libNativeGuard.so (???) (BuildId: f5a66a6326e3b02a2c87ad374937224cef0e4df8)
                                                                                                    runtime.cc:676]   native: #13 pc 0000000000032333  /data/app/~~uwBAHh5UHxiDay8_yvHIog==/id.kuro.androidnativeguard-XjDfxUx1gjiddkaGTYJzsQ==/lib/x86_64/libNativeGuard.so (???) (BuildId: f5a66a6326e3b02a2c87ad374937224cef0e4df8)
                                                                                                    runtime.cc:676]   native: #14 pc 0000000000032c00  /data/app/~~uwBAHh5UHxiDay8_yvHIog==/id.kuro.androidnativeguard-XjDfxUx1gjiddkaGTYJzsQ==/lib/x86_64/libNativeGuard.so (???) (BuildId: f5a66a6326e3b02a2c87ad374937224cef0e4df8)
2024-04-22 19:57:01.581  9350-9350  roidnativeguard         id.kuro.androidnativeguard           A  runtime.cc:676]   native: #15 pc 0000000000033258  /data/app/~~uwBAHh5UHxiDay8_yvHIog==/id.kuro.androidnativeguard-XjDfxUx1gjiddkaGTYJzsQ==/lib/x86_64/libNativeGuard.so (JNI_OnLoad+136) (BuildId: f5a66a6326e3b02a2c87ad374937224cef0e4df8)
                                                                                                    runtime.cc:676]   native: #16 pc 00000000005fe404  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::LoadNativeLibrary(_JNIEnv*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, _jobject*, _jclass*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)+3748) (BuildId: 44bc52550248fc712a381bef164b75c7)
                                                                                                    runtime.cc:676]   native: #17 pc 0000000000005c60  /apex/com.android.art/lib64/libopenjdkjvm.so (JVM_NativeLoad+384) (BuildId: 35ed32b49c4f94f82b61578dcca6e932)
                                                                                                    runtime.cc:676]   at java.lang.Runtime.nativeLoad(Native method)
                                                                                                    runtime.cc:676]   at java.lang.Runtime.nativeLoad(Runtime.java:1121)
                                                                                                    runtime.cc:676]   at java.lang.Runtime.loadLibrary0(Runtime.java:1075)
                                                                                                    runtime.cc:676]   - locked <0x06ffba36> (a java.lang.Runtime)
                                                                                                    runtime.cc:676]   at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    runtime.cc:676]   at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    runtime.cc:676]   at id.kuro.androidnativeguard.MainActivity.onCreate(MainActivity.java:20)
                                                                                                    runtime.cc:676]   at android.app.Activity.performCreate(Activity.java:8305)
                                                                                                    runtime.cc:676]   at android.app.Activity.performCreate(Activity.java:8284)
                                                                                                    runtime.cc:676]   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
                                                                                                    runtime.cc:676]   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
                                                                                                    runtime.cc:676]   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
                                                                                                    runtime.cc:676]   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    runtime.cc:676]   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    runtime.cc:676]   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    runtime.cc:676]   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
                                                                                                    runtime.cc:676]   at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    runtime.cc:676]   at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    runtime.cc:676]   at android.os.Looper.loop(Looper.java:288)
                                                                                                    runtime.cc:676]   at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    runtime.cc:676]   at java.lang.reflect.Method.invoke(Native method)
                                                                                                    runtime.cc:676]   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    runtime.cc:676]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by aimardcr** [comment]
Can you build without symbols stripped and try again?
